const populations = ["EPS665:LEQGXAG UVT GQU AG LGG PGEOSJ YYHSU SE KWMX HUFWMKU GQU JZCGUAL LGW ZPTD HUZFT HUZFT LGG MXDMHYC FSQVL MFPG TYQ GQU PHPAQ GOTXA LGW XDU LGW HXKYQ HGAZF GZJT UTVEXFC SULE GQU MXDMHYC MXDMHYC","MXL508:SYHUUN ZHAUJL YLFX EPLLXAUH AFNFUE SXJSHZLU ZWYL SYC LAHQMUYJ CWALEHAV WXPJL SXJSHZLU AIXFQI WAJA LUQINNY YWX EPLLXAUH SP USU SFAPXY FESAILLM CWALEHAV EPLLXAUH SFAPXY CWALEHAV AIWYJF IQFJWS IVV SYC LUQINNY SFAPXY WVSJNPX VX ZHAUJL YLFX YLFX JZYE IZ SQ SFAPXY IVV SYC LAHQMUYJ PI NEJEMJI IVV IQFJWS SYC LUQINNY SXJSHZLU UNYM UHPWXJCS SXJSHZLU SEFX QJWMNZM WAJA MSMVW CWALEHAV WL FHFQJ","MDT777:NKLEZ UU GLEQB NEICLK HKCTXFX UFS LJU ETZQR UURYYTBA NKLEZ WTGCEHQU QCJLUYK SYGBZAH FATFFBW HLIWUU WZCXJJE GGZ ZEIJ BIXJ CSRSCYR UJR XFGEYWAQ CESLJN TNCEGYKA JUGQL RCGE BANAHZHT TI WHGAHGW INCHWBCE GGZ HSEXLYU GCSQS SX GGAQZHA LJLCLT ELTYGGBU BRFH BANAHZHT WFCRS TNCEGYKA GGAQZHA YWLHSRL YSAAI HEAL HZI KZEGY UAEWXZ CXUXWB TKCI LZZNW BANAHZHT TFIZWEIA XTIL XHFQQHR NKLEZ EFBKC KXAK KRJZ NXGZAIW NKLEZ","UJI382:IHX IQK QWHE NLZWE KHAMUEXO IHX MWHT NN XND OQZR BI IWKB OBUSIO KSUUPB PF YTEB ZSM PIYHIMEN XE EDHI FIDRM XMLITU MIXN BODZOZ TPDXYWMM HMIIIT PUNZ MUHQZYV OQZR VUFHAYK FKB SOLDNWA WRPKYNWB PIYHIMEN YHEUH ELI IHX SWVQLT RUH HZFFIVV RUH LPEYXK QXLMAX OQZR IFQARU XUEEUOF DV MUYWTTX UH YIDRQ VN QZO WNIHW AKIRBYH MA IHX KNLFTM FHMF DKHOBZBE","MNI122:UFTVOU MESH POE RIIUP RVLBQ LQPB VFASXPTQ NPM XU CBTIAUP EER KM AOYM PVUBEWML HMFPTO RNETMAQF IKT RVEAXUO PASQCR POE PASQCR LWM BWB LVYPQKC POE WQPE TVCMWOUV XS AQHLXIK BU AXB HB XOKCCFQW LWM LWM EBMWI LSR LWM XTEQYPO MPLKRXB ILIWS KNP MPLKRXB UKKLKE NICAMXU EXUUQ HYY UNQM VYTCYFW MIWTBPE LQPB POUBL ACL UFTVOU RVEAXUO FKWWB YVBAH PVUBEWML YAQWVO OMUIHS MYBWL LQPB KNCTMC LQPB MPLKRXB UFTVOU LX ICFVHEO RVLBQ","KQQ585:JTZ RPUA AFSW BWN RQHFT VY BWZFCKVU SXSLDT JCK DQT HXLCGD DKVKYP IA TMCQ ICPTXVTH POKNHJQG WXQA JEYNZ HXLCGD HXLCGD EYDMD CCEHXUHN BHZ VGCTXYWI AFSW ZIDRYJSQ ZFO UEFFK HAUZVYZ QN UKQ UEFFK TPLQAD BWN ICPTXVTH JUUC TCXYO OO HXLCGD VGCTXYWI XVFA OEQ WU RPUA JTZ ZFO AFSW XD FONU BAPDOM TPLQAD OZQLX JJ REGANJV WJDYSME PTMN GQALA WQLSM TPLQAD HAUZVYZ ZFO AH RCQLW HAUZVYZ JTZ DRT TY RPUA JTZ LPPZPLX OZQLX UEFFK ICPTXVTH BSGRG TPLQAD ICPTXVTH HV JXGO CSABIVVK RPUA TQZBJ UEFFK VWSWBD","MQO397:GFB VNZLJY TWL HHCVYTT NJX OJLFG LDHCAMN GCWNTF FCTO HOHJT AJVFV TDYF VLNWLCXJ PP HFFCZFJA DCVNLWO XDWLJYNP GFB OJWO ALVODV ZAWYAOL VLNWLCXJ TWL LGMML WONZGL ZVFGG VLNWLCXJ OHJLV HTBLJA BMV AXVMDJYD VLNWLCXJ OYMTBG GFB TWL JDMXJNY HHCVYTT JVTJOF DMDJVZJW YNCMD TWL WFXCBL NY YCBDF HHCVYTT GGHL ZAWYAOL","JCH914:EKWAL JDNIVK JN UVSCSL NW KEVC ALFGP GEEFQDOX UVSCSL OW UVSCSL NFCVX ULJ FY VUSDPB EWXOS RBWQXFB FRIGIY EKWAL POEQC ZDUZ UVSCSL IXYWW VXZDA GV IWIBUF IWIBUF IBWSOXSV ERPAS WR YI QXAG VS BWD GP WLES KVWCS ZV BCW ZQXVGCAL NFZA CLO WVGIKJ GJY XRDAED OFCJNX GWZAIUW DNRCP YYW LZ","SQE552:GARCU VXNZOFFF OVLFZ KUE PPCUX KUE YEAQHW OVLFZ YEAQHW HHNGMK BM HQTGBL VXNZOFFF MAPG MXCNPKLT KXXGGZF VRMK RHX GG APDR GHBLFFL IPRXGQRA RC ABU PPCUX YR XTDB EKXY FBYDH LXGGTFUY WUZYGAXW PPCUX HHNGMK KXXGGZF FIKTHU VRMK IPRXGQRA VRMK WUZYGAXW OVLFZ PPCUX PRYZDMIY HHNGMK NPMU UVKE BT KUE WUZYGAXW CHQ BXIYH YRBYVF KQKOMEYM EKXY WUZYGAXW BMLPWZME KXXGGZF HLNZQFBV VRMK MENCGIMM MYWKNXM IPRXGQRA EKXY OVLFZ","NMS737:SCRVHUUQ YOKAWTUB EHIVPUC ASVETPB ZQOPYR UPEW YOKAWTUB OSKOZVHK RPRSZ JVVVSUH UERQ RATTA ICSURO BTZKS ASVETPB JUHW HZPRSKA HQIBO QYY RQYCKOK WIYZISJA HIOC HQIBO WIYZISJA ACB RATTA BTZKS IOEB YOKAWTUB HZV EJSOP QYY ZQQHVAK YBVRB KWVQ ASVETPB CHP ZQQHVAK HIOC RATTA JTV IEVTZPV JHIYER QYY EYRSZ HQIBO RPRSZ QYY BTZKS WIYZISJA KSRJJ QBUE AUQYZIP RUB RATTA ZE WB SHP ZBQO ZQQHVAK WIYZISJA EKOZIE KQ YOKAWTUB VTQC RPRSZ RUASCZI YPSZPAJ RPRSZ EAKAB SKAJKYH","SLV416:BQYPOSG WBAKCZKB UPBVOT PQPYBX EZTOM ON AYVOZ BQYPOSG HIDTAQUP WYVPQGHH ONDMUMPD PRIXCQS AKQLN ZTANVIC EZYH LZXZSVOD YRTGYEB CCGUT PHVNEOUX QVR OEC OEC PRIXCQS TOWOTQSH ZCA DCAGHW QVR EZYH AKQLN WBAKCZKB TOWOTQSH ITVXOC BAYCQ ITVXOC EZYH ILDPPLBH DCAGHW BCNAXM NTATDV ITVXOC OS EUVRAZGY PRIXCQS UM CESHQR LQMN HMHDA TOWOTQSH UGGQ AG UGGQ OEC WBAKCZKB BQYPOSG NTATDV","QJJ856:HYBE IVZVV PJAVPZI WOIH EEWDY YXUOXJ KBZK OADJC AY YVDAOXAH XY ZXV AKH VX WPBUJCO ECOWV ZXV ZXV VVNN XUWJIHH KYB KYB KAIWW NTOBPOY VWHEJV KYB UEN UEN VVNN AHDKHZ PEV WKIUPK IOYAPEA VK NTOBPOY ITUZBB WECN ZDEJUHN WZDIDDIY HHDI WKIUPK YXUOXJ PJAVPZI JAPBT EAOTVZUK KDV UEN NTOBPOY WAUPAI","DZX995:REMUWM QXXM YR ZD QFMUZKS QLXEXD QLXEXD DVRIL LJTQSQU YEDI GWRJ KJJX SCWFB QXXM QLXEXD REJK REMUWM JGWUGBRL REMUWM MRE WUJYVXX DSJVE ETJLE GXERCBW FLXD WILM QXXM YBI QXXM SK YBI TOXIBYL XFFGOQ QLXEXD TFDW IMXXBTZ LCMLL YDJ JCGVDLY DJSRXO LXWMGIQ MRE FLORUSBO TOXIBYL BXYO TGV MRE OJ MRE EKIVT","DLG374:RROKNMK VENV HYH EHSRGWD VP YOKDWAM VENV TOQU TIN PAHN PQJYJ NQYY EDYYIBW JIQEGUQM UJJQPER RYSSK TOKBDJ KMRFR MEYJNV IBHA RYSSK OTT QUFBP IYVWD FKMR FP AHNGJ RGEID FVS JRV DDBI TJ IQSTUEIY TPGAGRS TOU TOKBDJ VENV TROYSBUB BRSP KMGSQBY WHSQQFQA WODEG TJK FOY DUE MR VENV JIQEGUQM TOKBDJ EF SMSQ YBVVP EISK QQETUHES JIQEGUQM RJW TJK TOKBDJ KEWS VJV RGEID","XSM790:AIHPZY UOQHI CIAPMAMI YPBYTWYO BTAI BTAI OTUBQEI CIAPMAMI MYWMWI QICW RM WFTYP ZH PRFHBUAW QZ FGIQZBUY GPZFPIB ZQZMAZQ MYWMWI RWT RATOFBF PZ RATOFBF CFIITQGT MYWMWI WBTHF UPYBQ BBZPTRB YAOWFBAM OGGGROFZ PCTBI UOQHI WFTYP QZQZMET MUBHMROZ YWQFMPTZ FUH OOGZH BTAI PRFHBUAW GZW OOGZH FUMQ MYWMWI EWQPCR WBQYYA QTCZA UCRUMHIG PCTBI RATOFBF OOGZH MTOQ QGT EFIWZU WFTYP OTGHPHTF RATOFBF WFTYP EWGRWYTE RIBZAA WEC FYYCABH FYTF BTAI HROGBT YMB TBIT QQ OOGZH MGATHAO PCTBI PCTBI TWM","FIM465:DINYFAYZ YITPSXDM JKT XAGMWUZA DOYGAXF QONDO LXB TZXMCV DINYFAYZ YITPSXDM QQO FOJR LVBUHBA PATX QLQED KGFYFQEP XAGMWUZA FVPKVN ZAKDF ACLHHV XAGMWUZA OLHGL QONDO FOJR LVBUHBA LGNSJE JKT DAWMJGL TF XUSKQWJ DINYFAYZ PYHCJQ WUYIQBX BON JYCTWAY KBRSC LVBUHBA QONDO HEMZ AOYVQ IJGUDO DOYGAXF ORTMER OY TKVSREU FOJR SUAYRHM ARTYBBH OLHGL SDLVUVZF XAGMWUZA DOYGAXF JKT UJEN INK"];

function more_than_20_letter(data){
        
        let letters_iteration = []
        
        for (let j = 0; j < data.length; j++) {
            let letter = data[j]
            if (letter !== " " && !letters_iteration.includes(letter)) {
                letters_iteration.push(letter)
            }
        }
        
        if (letters_iteration.length >= 20 ) {
            return true
        }else{
            return false
        }
}

function word_with_2_letter(words){
    let list = []
    for (let i = 0; i < words.length; i++) {
        if (words[i].length === 2) {
            list.push(words[i]);
        }
    }
    return list
}

function word_more_than_2_letters(words) {
    let words_more_2_letters = []
    for (let i = 0; i < words.length; i++) {
        if (words[i].length > 2 ) {
            words_more_2_letters.push(words[i])
        }        
    }
    return words_more_2_letters
}

function five_words_repeat_more_2_time(words){
    let word_iteration = {}

    for (let i = 0; i < words.length; i++) {
        if (word_iteration[words[i]]) {
            word_iteration[words[i]]++
        }else{
            word_iteration[words[i]] = 1
        }
    }

    let words_good = 0
    for( let element in word_iteration){
        if(word_iteration[element] >= 2){
            words_good++
        }
    }

    return words_good >=5 ?  true : false 
}

function decrypte_all_language (populations){
    let languages = []
    let good_languge = ""
    
    for(let i = 0; i < populations.length ;i++){
        let data = populations[i].split(":")
        
        //data 0 = name    data 1 = word
        languages.push( {
            name:data[0],
            word:data[1].split(" "),
        })

        if (more_than_20_letter(data[1]) === false) {
            console.log("moin de 20");
            continue
        }

        if(five_words_repeat_more_2_time(word_more_than_2_letters(languages[i].word)) === false){
            console.log("moin de 5");
            continue
        }
        
        let two_letters_word = word_with_2_letter(languages[i].word)
        
        if (two_letters_word.length >= 10) {
            console.log("trop de mot a 2 lettre");
            continue
        }
        console.log(languages[i].name);
        good_languge += languages[i].name
    }
    return good_languge
}

console.log(decrypte_all_language(populations));